### ISSUE TITLE
loadService() issue

### ISSUE THREAD

**Issue by dereuromark** [burzum/cakephp-service-layer#13]
We had loadService() in a loop, expecting it to behave like loadModel() just returning the service if already created.

> Warning (512): App\Release\Releaser::$%s is already in use. in [/.../vendor/burzum/cakephp-service-layer/src/Service/ServiceAwareTrait.php, line 66] 

Do you think we can just 

    return $this->{$name} 

here, as well?

```php
if (isset($this->{$name})) {
    //trigger_error(__CLASS__ . '::$%s is already in use.', E_USER_WARNING);
    return $this->{$name};
}
```

**Comment by dereuromark** [comment]
Also sprintf() $name part is missing it seems.

**Comment by saeideng** [comment]
could we check type of service and model and throw a warning just when it was cake's normal model ?

**Comment by dereuromark** [comment]
I dont think core one has checks here, if the instance is available it is reused. Simple as that.

**Comment by saeideng** [comment]
@dereuromark  
for me that use both model and service together 
throwing a warning/error helps me to avoid not using incorrectly model as service  :)
I use this plugin in existing program , and I can not port all model usage in controller to use service right now

**Comment by dereuromark** [comment]
I see... well, as long as that notice is only on one side, the other side can still happen.
IMO we should check instance of maybe then and throw exception then
But otherwise if the same correct one already exists, no warning should be produced.

**Comment by dereuromark** [comment]
@burzum Can we remove this warning? And instead just check if the type is correct? And we dont reuse the wrong type of class here?

**Comment by burzum** [comment]
@dereuromark So you problem is actually that the magic __call() check is used by the model and service aware traits? I would remove the warning but not use the interface. If it's already assigned just return the value as you said.

However, I dislike that kind of behavior but it's essentially what Cake loves to do. So let's comply with it.

This whole plugin is a crutch to have something like a service being loadable trough a locator instead of using a DI container that is either directly accessed ($this->getContainer()->get(MyThingInterface::class)) or passed to the constructor and auto-resolved by the DI container through auto-wiring / reflections. (__construct(MyThingInterface $myThing)).

**Comment by dereuromark** [comment]
Yes, we should remove at least the warning for now.
We need this fix for us here.

**Comment by dereuromark** [comment]
PR open.
